// _render-fields.mjs — defines what Chronicle's reference browser can
// display, and how this package's structured data is flattened for it.
//
// Chronicle renders a property via propString(props, key) =
// fmt.Sprintf("%v", props[key]), for every key in a manifest category's
// `fields`. A field key MUST exist in the data and hold a scalar: a missing
// key renders as a silent blank, and a non-scalar prints Go syntax garbage
// (`map[…]`, `<nil>`).
//
// Where an entry's substance is nested, the structured value stays put
// (widgets/Foundry sync read it) and this module derives a scalar
// `<key>_display` twin for the manifest to point at instead — generated by
// build-render-fields.mjs, pinned by test-render-contract.mjs. The
// `_display` suffix (not `_text`) avoids colliding with authored
// `<key>_text` fields.

// ---------------------------------------------------------------------------
// Reference markup
// ---------------------------------------------------------------------------
//
// This package's text fields carry `{@category term}` / `{@category
// term|label}` cross-reference markup (CLAUDE.md -> "@Reference Syntax").
// Widgets resolve it via reference-renderer.js into a tooltip span; Chronicle's
// reference browser has no such step and prints it as literal text
// (system_pages.templ's propString / item.Summary). So the STRUCTURED value
// keeps its markers (widgets need them), and the generated `<key>_display`
// twin — all Chronicle ever sees — carries the resolved text. A key whose
// value contains a marker gets a twin even when already scalar.

/**
 * REF_MARKER matches one reference marker. Must stay character-for-character
 * identical to REF_PATTERN in widgets/reference-renderer.js, or the twin and
 * the widget disagree about what a marker is. test-render-contract.mjs pins
 * them against each other by reading the widget source.
 */
export const REF_MARKER_SOURCE = '\\{@(\\w+)\\s+([^|}]+)(?:\\|([^}]+))?\\}';

/**
 * flattenRefs resolves reference markup down to the words it displays:
 *
 *   "{@combat dying}"             -> "dying"
 *   "{@condition taunted|taunts}" -> "taunts"
 *
 * i.e. the label reference-renderer.js puts in its tooltip span, minus the
 * span. Non-strings and marker-free strings pass through unchanged. Resolves
 * from the marker's own text, not a glossary lookup, so the sentence stays
 * grammatical ("{@combat dying}" reads as "dying", not the glossary's
 * title-cased "Dying").
 */
export function flattenRefs(text) {
  if (typeof text !== 'string' || !text.includes('{@')) return text;
  return text.replace(new RegExp(REF_MARKER_SOURCE, 'g'), (_m, _cat, term, label) =>
    String(label ?? term).trim(),
  );
}

/** True when a value still carries markup Chronicle would print literally. */
export function hasRefMarkers(v) {
  return typeof v === 'string' && v.includes('{@');
}

// ---------------------------------------------------------------------------
// Scalar rendering
// ---------------------------------------------------------------------------

/** True for the JSON types propString can format into human text. */
export function isScalar(v) {
  return typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean';
}

/** "stamina_per_level" -> "stamina per level" — labels inside a rendered blob. */
function humanKey(k) {
  return k.replace(/_/g, ' ');
}

// Keys that lead a rendered object (its title) and keys that form its body.
// Checked in order, so {name, description} reads "Name — description" rather
// than "name: Name; description: …".
const LEAD_KEYS = ['name', 'label', 'title', 'term'];
const BODY_KEYS = ['description', 'text', 'note'];

/**
 * renderValue turns any JSON value into one line of human-readable text.
 * Deliberately generic rather than per-file, so there's no bespoke formatter
 * to forget to update. Deterministic, so the drift test can recompute it.
 *
 *   scalar            -> "5"
 *   [scalars]         -> "Attack, Magic, Melee"
 *   {name, cost, description}
 *                     -> "Beast Legs (cost 1) — Your powerful legs …"
 *   [objects]         -> the above, joined with " · "
 *   {a: 1, b: 2}      -> "a: 1; b: 2"
 *
 * Returns "" for null/undefined and for empty arrays/objects, which callers
 * treat as "omit the key entirely" — an absent key renders as a skipped detail
 * row, whereas a present-but-empty one would render as a blank cell.
 */
export function renderValue(v) {
  if (v === null || v === undefined) return '';
  if (isScalar(v)) return String(v);

  if (Array.isArray(v)) {
    const parts = v.map(renderValue).filter((s) => s !== '');
    if (!parts.length) return '';
    // A list of plain scalars reads as a comma list; anything richer gets the
    // stronger separator so the commas inside each part stay legible.
    return v.every(isScalar) ? parts.join(', ') : parts.join(' · ');
  }

  if (typeof v === 'object') {
    const entries = Object.entries(v).filter(([, val]) => val !== null && val !== undefined);
    if (!entries.length) return '';
    const obj = Object.fromEntries(entries);

    const leadKey = LEAD_KEYS.find((k) => typeof obj[k] === 'string' && obj[k] !== '');
    const bodyKey = BODY_KEYS.find((k) => typeof obj[k] === 'string' && obj[k] !== '');

    const used = new Set([leadKey, bodyKey].filter(Boolean));
    const rest = entries
      .filter(([k]) => !used.has(k))
      .map(([k, val]) => {
        const s = renderValue(val);
        return s === '' ? '' : `${humanKey(k)}: ${s}`;
      })
      .filter((s) => s !== '');

    if (!leadKey) return rest.join('; ');

    // "Lead (rest) — body" when there is a body to set off; "Lead — rest" when
    // there isn't, so an object that is all attributes (a kit's signature
    // ability) doesn't read as one long parenthetical.
    if (!bodyKey) return rest.length ? `${obj[leadKey]} — ${rest.join('; ')}` : obj[leadKey];
    let out = obj[leadKey];
    if (rest.length) out += ` (${rest.join('; ')})`;
    return `${out} — ${obj[bodyKey]}`;
  }

  return String(v);
}

// ---------------------------------------------------------------------------
// Derived summaries
// ---------------------------------------------------------------------------

/**
 * Suffix naming a MACHINE-DERIVED scalar twin. Deliberately not `_text`:
 * some entries author their own prose for a structured value (e.g.
 * encounter-building.json's `budget_band_text`), and keeping the namespaces
 * separate lets the generator own `_display` completely without overwriting
 * authored words.
 */
export const DERIVED_SUFFIX = '_display';

/** Suffix reserved for an AUTHORED prose rendering of a structured value. */
export const AUTHORED_SUFFIX = '_text';

/** Provenance bookkeeping, folded into one "Provenance Notes" column. */
export const PROVENANCE_KEYS = ['custom_fields', 'derived_from', 'omissions'];

/** The two aggregate columns the builder derives. */
export const DETAILS_KEY = 'details' + DERIVED_SUFFIX;
export const PROVENANCE_KEY = 'provenance' + DERIVED_SUFFIX;

/**
 * displayKeyFor names the scalar property key a manifest category must
 * declare to display data key `key`: the key itself when scalar, its
 * authored `<key>_text` if present, else the derived `<key>_display`. Pure,
 * so the builder and the test agree without sharing state.
 *
 * `flattened` is the set of data keys carrying reference markup anywhere in
 * the file; those always resolve to the derived twin regardless of shape,
 * since only the generated twin is flattened.
 *
 * The verdict is per FILE, not per entry — a per-entry verdict would declare
 * the bare key whenever the first carrier happened to be marker-free, and
 * every later marker-bearing entry in that column would print raw markup.
 */
export function displayKeyFor(properties, key, flattened) {
  const v = (properties || {})[key];
  if (v === undefined || v === null) return null;
  const forced = flattened instanceof Set ? flattened.has(key) : Boolean(flattened);
  if (!forced) {
    if (isScalar(v)) return key;
    if (typeof properties[key + AUTHORED_SUFFIX] === 'string') return key + AUTHORED_SUFFIX;
  }
  return key + DERIVED_SUFFIX;
}

/**
 * columnsNeedingFlattening returns the category's column keys that carry
 * reference markup in at least one entry — the keys whose manifest field must
 * point at a flattened twin. Also checks the authored `_text` phrasing, which
 * a twin would otherwise be built from.
 */
export function columnsNeedingFlattening(items, category) {
  const hit = new Set();
  for (const [dataKey] of category?.columns || []) {
    const found = items.some((it) => {
      const p = it.properties || {};
      if (p[dataKey] === undefined) return false;
      return hasRefMarkers(renderValue(p[dataKey])) || hasRefMarkers(p[dataKey + AUTHORED_SUFFIX]);
    });
    if (found) hit.add(dataKey);
  }
  return hit;
}

/**
 * foldEntries renders a set of properties into one "k — v · k — v" scalar,
 * for the two aggregate columns (see CATEGORIES). Always flattened: the
 * output is only ever printed by Chronicle, never read structurally.
 */
export function foldEntries(properties, keys) {
  return flattenRefs(
    keys
      .map((k) => [k, renderValue(properties[k])])
      .filter(([, s]) => s !== '')
      .map(([k, s]) => `${humanKey(k)} — ${s}`)
      .join(' · '),
  );
}

/** Longest summary we will derive before truncating. */
export const SUMMARY_MAX = 180;

/**
 * deriveSummary produces the one-line `summary` the list table's Summary
 * column renders (system_pages.templ prints item.Summary for every row).
 * First sentence of the description, truncated on a word boundary, so it
 * cannot drift from the description it summarizes; an entry with its own
 * non-empty summary keeps it.
 */
export function deriveSummary(description) {
  const text = String(description || '').replace(/\s+/g, ' ').trim();
  if (!text) return '';
  if (text.length <= SUMMARY_MAX) return text;

  // Prefer a sentence boundary that lands inside the budget.
  const stop = text.slice(0, SUMMARY_MAX + 1).search(/[.!?](\s|$)/);
  if (stop > 40) return text.slice(0, stop + 1);

  const cut = text.lastIndexOf(' ', SUMMARY_MAX - 1);
  return text.slice(0, cut > 40 ? cut : SUMMARY_MAX - 1).trimEnd() + '…';
}

// ---------------------------------------------------------------------------
// What the reference browser shows, per dataset
// ---------------------------------------------------------------------------

/**
 * CATEGORIES declares every browsable dataset: its data file, label, and
 * which property keys become columns. build-render-fields.mjs generates the
 * derived data fields and manifest.json's `categories` from it, so the
 * manifest can never name a key the data lacks.
 *
 * `columns` names the structured key; each resolves to a scalar
 * `<key>_display` (see displayKeyFor) since propString can't print objects.
 * `fold: true` adds a "Details" column folding ungrouped keys into one
 * string, for datasets whose entries don't share a key set.
 *
 * Keep column counts low: the list table is `w-full` inside
 * `overflow-hidden`, so extra columns squeeze the rest instead of scrolling.
 */
export const CATEGORIES = [
  {
    file: 'abilities.json',
    slug: 'abilities',
    name: 'Abilities',
    icon: 'fa-bolt',
    fold: true,
    // cost_amount / cost_resource are the machine-readable halves of `cost`
    // ("5 Wrath"), kept for widgets. Folding them into Details would print
    // "cost amount — 5 · cost resource — Wrath" under a Cost row that already
    // says it, on 361 of 519 abilities.
    foldExclude: ['cost_amount', 'cost_resource'],
    columns: [
      ['category', 'Granted By', 'string'],
      ['class', 'Class', 'string'],
      ['level', 'Level', 'number'],
      ['type', 'Type', 'string'],
      ['action_type', 'Action', 'string'],
      ['cost', 'Cost', 'string'],
      ['keywords', 'Keywords', 'string'],
      ['distance', 'Distance', 'string'],
      ['target', 'Target', 'string'],
      ['power_roll', 'Power Roll', 'string'],
      ['tier1', 'Tier 1 (11 or lower)', 'string'],
      ['tier2', 'Tier 2 (12-16)', 'string'],
      ['tier3', 'Tier 3 (17+)', 'string'],
      ['effect', 'Effect', 'string'],
      ['trigger', 'Trigger', 'string'],
    ],
  },
  {
    file: 'ancestries.json',
    slug: 'ancestries',
    name: 'Ancestries',
    icon: 'fa-dna',
    fold: true,
    columns: [
      ['size', 'Size', 'string'],
      ['speed', 'Speed', 'number'],
      ['stability', 'Stability', 'number'],
      ['ancestry_points', 'Ancestry Points', 'number'],
      ['quick_build', 'Quick Build', 'string'],
      ['signature_traits', 'Signature Traits', 'string'],
      ['purchased_traits', 'Purchased Traits', 'string'],
    ],
  },
  {
    file: 'kits.json',
    slug: 'kits',
    name: 'Kits',
    icon: 'fa-toolbox',
    columns: [
      ['type', 'Type', 'string'],
      ['armor', 'Armor', 'string'],
      ['weapon', 'Weapon', 'string'],
      ['equipment', 'Equipment', 'string'],
      ['stamina_bonus', 'Stamina Bonus', 'number'],
      ['stamina_bonus_scaling', 'Stamina Scaling', 'string'],
      ['speed_bonus', 'Speed Bonus', 'number'],
      ['stability_bonus', 'Stability Bonus', 'number'],
      ['melee_damage_bonus', 'Melee Damage', 'string'],
      ['ranged_damage_bonus', 'Ranged Damage', 'string'],
      ['melee_distance_bonus', 'Melee Distance', 'number'],
      ['ranged_distance_bonus', 'Ranged Distance', 'number'],
      ['disengage_bonus', 'Disengage Bonus', 'number'],
      ['signature_ability', 'Signature Ability', 'string'],
    ],
  },
  {
    file: 'creatures.json',
    slug: 'creatures',
    name: 'Creatures',
    icon: 'fa-paw',
    columns: [
      ['level', 'Level', 'number'],
      ['organization', 'Organization', 'string'],
      ['role', 'Role', 'string'],
      ['ev', 'EV', 'number'],
      ['size', 'Size', 'string'],
      ['stamina', 'Stamina', 'number'],
      ['speed', 'Speed', 'number'],
      ['free_strike', 'Free Strike', 'string'],
      ['keywords', 'Keywords', 'string'],
      ['traits', 'Traits', 'string'],
    ],
  },
  {
    file: 'creature-abilities.json',
    slug: 'creature-abilities',
    name: 'Creature Abilities',
    icon: 'fa-burst',
    columns: [
      ['type', 'Type', 'string'],
      ['keywords', 'Keywords', 'string'],
      ['distance', 'Distance', 'string'],
      ['target', 'Target', 'string'],
      ['power_roll', 'Power Roll', 'string'],
      ['tier1', 'Tier 1 (11 or lower)', 'string'],
      ['tier2', 'Tier 2 (12-16)', 'string'],
      ['tier3', 'Tier 3 (17+)', 'string'],
      ['effect', 'Effect', 'string'],
      ['trigger', 'Trigger', 'string'],
      ['villain_action_order', 'VA Order', 'string'],
    ],
  },
  {
    file: 'animal-traits.json',
    slug: 'animal-traits',
    name: 'Animal Traits',
    icon: 'fa-hippo',
    fold: true,
    columns: [
      ['group', 'Group', 'string'],
      ['cost', 'Cost', 'number'],
      ['repeatable', 'Repeatable', 'number'],
      ['upgrade', 'Upgrade', 'string'],
      ['optional', 'Optional', 'string'],
      ['granted_ability', 'Granted Ability', 'string'],
    ],
  },
  {
    file: 'ancestry-point-buy.json',
    slug: 'ancestry-point-buy',
    name: 'Ancestry Point Buy',
    icon: 'fa-scale-balanced',
    fold: true,
    // `category` is a constant marker on every entry of the file and just
    // repeats the category name the page is already under.
    foldExclude: ['category'],
    columns: [['rule_type', 'Rule Type', 'string']],
  },
  {
    file: 'monster-building.json',
    slug: 'monster-building',
    name: 'Monster Building',
    icon: 'fa-dragon',
    fold: true,
    // `category` is a constant marker on every entry of the file and just
    // repeats the category name the page is already under.
    foldExclude: ['category'],
    columns: [
      ['rule_type', 'Rule Type', 'string'],
      ['formula', 'Formula', 'string'],
      ['rounding', 'Rounding', 'string'],
    ],
  },
  {
    file: 'encounter-building.json',
    slug: 'encounter-building',
    name: 'Encounter Building',
    icon: 'fa-chess-board',
    fold: true,
    // `category` is a constant marker on every entry of the file and just
    // repeats the category name the page is already under.
    foldExclude: ['category'],
    columns: [
      ['rule_type', 'Rule Type', 'string'],
      ['difficulty', 'Difficulty', 'string'],
      ['budget_band', 'Budget Band', 'string'],
      ['victories', 'Victories', 'string'],
    ],
  },
  {
    file: 'rules-glossary.json',
    slug: 'rules-glossary',
    name: 'Rules Glossary',
    icon: 'fa-book',
    // The definition itself is the root `description`, which the detail page
    // renders on its own and the list table shows through the derived summary.
    // The category it belongs to is all the table needs to add.
    columns: [['category', 'Category', 'string']],
  },
  {
    file: 'skills.json',
    slug: 'skills',
    name: 'Skills',
    icon: 'fa-graduation-cap',
    columns: [['group', 'Group', 'string']],
  },
  {
    file: 'ability-keywords.json',
    slug: 'ability-keywords',
    name: 'Ability Keywords',
    icon: 'fa-tags',
    columns: [
      ['group', 'Group', 'string'],
      ['note', 'Note', 'string'],
    ],
  },
  {
    file: 'creature-keywords.json',
    slug: 'creature-keywords',
    name: 'Creature Keywords',
    icon: 'fa-hashtag',
    // No properties at all: name + the derived summary + the root description
    // on the detail page are the entire entry.
    columns: [],
  },
];

/** CATEGORIES indexed by data filename. */
export const CATEGORY_BY_FILE = new Map(CATEGORIES.map((c) => [c.file, c]));

// ---------------------------------------------------------------------------
// Which files the reference browser shows
// ---------------------------------------------------------------------------

/**
 * WIDGET_ONLY names data/*.json files that are read by a widget or the
 * monster engine but are deliberately not reference categories (they'd show
 * implementation detail, not rules). Exhaustive: test-render-contract.mjs
 * requires every data file to be a manifest category or listed here.
 */
export const WIDGET_ONLY = new Set([
  // Root-field shape read directly by monster-engine.js and monster-builder.js.
  // Published equivalents are browsable as the monster-building category.
  'organization-templates.json',
  'role-templates.json',
  // One synthetic row of pre-computed numbers, consumed by monster-builder.js.
  'damage-baselines.json',
  // Rulebook UI content: layout blocks and a scripted example, consumed by the
  // rulebook-frontpage widget and the example player.
  'rulebook-frontpage.json',
  'rulebook-examples.json',
]);

/**
 * SOURCE_PENDING names the files whose entries do NOT yet carry provenance
 * (docs/DATA-SCHEMA.md's provenance rule). test-render-contract.mjs pins this
 * both ways: a sourced file must be removed, an unlisted file must be fully
 * sourced, so the set can only shrink and never gain a new file.
 */
export const SOURCE_PENDING = new Set([
  'rules-glossary.json',
  'skills.json',
  'creature-abilities.json',
  'creature-keywords.json',
  'rulebook-frontpage.json',
]);
