// _render-fields.mjs — the single definition of what Chronicle's reference
// browser can actually display, and how this package's structured data is
// flattened so that it does.
//
// WHY THIS EXISTS
// ---------------
// Chronicle renders a reference item's properties through exactly one helper
// (internal/systems/template_helpers.go):
//
//     func propString(props map[string]any, key string) string {
//         val, ok := props[key]; if !ok { return "" }
//         return fmt.Sprintf("%v", val)
//     }
//
// and the templ pages (internal/systems/system_pages.templ) call it for every
// key declared in the manifest category's `fields`, in BOTH the list table and
// the item-detail card. Three consequences follow, and all three are load-bearing:
//
//   1. A manifest field key that does not exist in the data renders as the
//      empty string — a blank table column and a silently omitted detail row.
//      Nothing errors. This is how 12 of 12 ancestries shipped with an empty
//      Traits column: the manifest declared `traits`, the data ships
//      `signature_traits` / `purchased_traits`.
//   2. `fmt.Sprintf("%v", …)` only produces human text for SCALARS. An object
//      becomes `map[cost:1 name:Beast Legs]`, an array of objects becomes
//      `[map[…] map[…]]`, an array of strings becomes `[Attack Melee]`, and a
//      JSON null becomes `<nil>`. All four are garbage on the page.
//   3. There is no detail-only field slot (the templ hardcodes a single
//      exception for the literal key "classes"), so every declared field is a
//      table column too.
//
// So: a manifest field key MUST point at a scalar. Where the substance of an
// entry lives in a nested shape — an ancestry's purchased traits, a kit's
// signature ability, an ability's keywords — the structured value stays put
// (widgets and the Foundry sync read it) and this module derives a scalar
// `<key>_display` twin beside it, which is what the manifest points at.
//
// The twins are generated by tools/build-render-fields.mjs and pinned by
// tools/test-render-contract.mjs, so a hand-edit to the structured value that
// forgets the twin fails CI rather than shipping a stale sentence.
//
// The derived twin is named `<key>_display`, not `<key>_text`, so that the
// generator can own its whole namespace without colliding with the handful of
// authored `<key>_text` fields that already phrase a structured value better
// than any generic formatter could.

// ---------------------------------------------------------------------------
// Scalar rendering
// ---------------------------------------------------------------------------

/** True for the JSON types propString can format into human text. */
export function isScalar(v) {
  return typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean';
}

/** "stamina_per_level" -> "stamina per level" — labels inside a rendered blob. */
function humanKey(k) {
  return k.replace(/_/g, ' ');
}

// Keys that lead a rendered object (its title) and keys that form its body.
// Checked in order, so {name, description} reads "Name — description" rather
// than "name: Name; description: …".
const LEAD_KEYS = ['name', 'label', 'title', 'term'];
const BODY_KEYS = ['description', 'text', 'note'];

/**
 * renderValue turns any JSON value into one line of human-readable text.
 *
 * Deliberately generic rather than per-file: the build-your-own datasets carry
 * a dozen one-off nested shapes (budget bands, fill rates, tier modifiers,
 * granted abilities) and a bespoke formatter for each would be a second place
 * to forget to update. Deterministic, so the drift test can recompute it.
 *
 *   scalar            -> "5"
 *   [scalars]         -> "Attack, Magic, Melee"
 *   {name, cost, description}
 *                     -> "Beast Legs (cost 1) — Your powerful legs …"
 *   [objects]         -> the above, joined with " · "
 *   {a: 1, b: 2}      -> "a: 1; b: 2"
 *
 * Returns "" for null/undefined and for empty arrays/objects, which callers
 * treat as "omit the key entirely" — an absent key renders as a skipped detail
 * row, whereas a present-but-empty one would render as a blank cell.
 */
export function renderValue(v) {
  if (v === null || v === undefined) return '';
  if (isScalar(v)) return String(v);

  if (Array.isArray(v)) {
    const parts = v.map(renderValue).filter((s) => s !== '');
    if (!parts.length) return '';
    // A list of plain scalars reads as a comma list; anything richer gets the
    // stronger separator so the commas inside each part stay legible.
    return v.every(isScalar) ? parts.join(', ') : parts.join(' · ');
  }

  if (typeof v === 'object') {
    const entries = Object.entries(v).filter(([, val]) => val !== null && val !== undefined);
    if (!entries.length) return '';
    const obj = Object.fromEntries(entries);

    const leadKey = LEAD_KEYS.find((k) => typeof obj[k] === 'string' && obj[k] !== '');
    const bodyKey = BODY_KEYS.find((k) => typeof obj[k] === 'string' && obj[k] !== '');

    const used = new Set([leadKey, bodyKey].filter(Boolean));
    const rest = entries
      .filter(([k]) => !used.has(k))
      .map(([k, val]) => {
        const s = renderValue(val);
        return s === '' ? '' : `${humanKey(k)}: ${s}`;
      })
      .filter((s) => s !== '');

    if (!leadKey) return rest.join('; ');

    // "Lead (rest) — body" when there is a body to set off; "Lead — rest" when
    // there isn't, so an object that is all attributes (a kit's signature
    // ability) doesn't read as one long parenthetical.
    if (!bodyKey) return rest.length ? `${obj[leadKey]} — ${rest.join('; ')}` : obj[leadKey];
    let out = obj[leadKey];
    if (rest.length) out += ` (${rest.join('; ')})`;
    return `${out} — ${obj[bodyKey]}`;
  }

  return String(v);
}

// ---------------------------------------------------------------------------
// Derived summaries
// ---------------------------------------------------------------------------

/**
 * Suffix naming a MACHINE-DERIVED scalar twin.
 *
 * Deliberately not `_text`: a handful of entries author their own prose
 * rendering of a structured value (encounter-building.json's
 * `budget_band_text` phrases a `{lower, upper, upper_inclusive}` band far
 * better than any generic formatter could). Keeping the two namespaces apart
 * means the generator can own `_display` completely — regenerating it from
 * scratch on every run, so a drift check is exact — without ever overwriting
 * authored words.
 */
export const DERIVED_SUFFIX = '_display';

/** Suffix reserved for an AUTHORED prose rendering of a structured value. */
export const AUTHORED_SUFFIX = '_text';

/** Provenance bookkeeping, folded into one "Provenance Notes" column. */
export const PROVENANCE_KEYS = ['custom_fields', 'derived_from', 'omissions'];

/** The two aggregate columns the builder derives. */
export const DETAILS_KEY = 'details' + DERIVED_SUFFIX;
export const PROVENANCE_KEY = 'provenance' + DERIVED_SUFFIX;

/**
 * displayKeyFor names the scalar property key a manifest category must declare
 * in order to display the data key `key`: the key itself when its value is a
 * scalar, its authored `<key>_text` when one exists, else the derived
 * `<key>_display`. Pure — it decides from the value's shape alone, so the
 * builder and the test agree without sharing state.
 */
export function displayKeyFor(properties, key) {
  const v = (properties || {})[key];
  if (v === undefined || v === null) return null;
  if (isScalar(v)) return key;
  if (typeof properties[key + AUTHORED_SUFFIX] === 'string') return key + AUTHORED_SUFFIX;
  return key + DERIVED_SUFFIX;
}

/**
 * foldEntries renders a set of properties into one "k — v · k — v" scalar.
 * Used for the two aggregate columns; see CATEGORIES for why they exist.
 */
export function foldEntries(properties, keys) {
  return keys
    .map((k) => [k, renderValue(properties[k])])
    .filter(([, s]) => s !== '')
    .map(([k, s]) => `${humanKey(k)} — ${s}`)
    .join(' · ');
}

/** Longest summary we will derive before truncating. */
export const SUMMARY_MAX = 180;

/**
 * deriveSummary produces the one-line `summary` the list table's Summary
 * column renders (system_pages.templ prints item.Summary for every row).
 * Without it that column is blank for every category except creatures, which
 * is the only file that authored one by hand.
 *
 * First sentence of the description, truncated on a word boundary. Derived
 * rather than authored so it cannot drift from the description it summarizes;
 * an entry that authors its own non-empty summary keeps it.
 */
export function deriveSummary(description) {
  const text = String(description || '').replace(/\s+/g, ' ').trim();
  if (!text) return '';
  if (text.length <= SUMMARY_MAX) return text;

  // Prefer a sentence boundary that lands inside the budget.
  const stop = text.slice(0, SUMMARY_MAX + 1).search(/[.!?](\s|$)/);
  if (stop > 40) return text.slice(0, stop + 1);

  const cut = text.lastIndexOf(' ', SUMMARY_MAX - 1);
  return text.slice(0, cut > 40 ? cut : SUMMARY_MAX - 1).trimEnd() + '…';
}

// ---------------------------------------------------------------------------
// What the reference browser shows, per dataset
// ---------------------------------------------------------------------------

/**
 * CATEGORIES is the single declaration of every browsable dataset: which data
 * file it is, how it is labelled, and which property keys become columns.
 * tools/build-render-fields.mjs generates BOTH the derived data fields and
 * manifest.json's `categories` array from it, so the manifest can no longer
 * name a key the data does not have — that mismatch is the whole reason this
 * file exists.
 *
 * `columns` names the STRUCTURED data key. The builder resolves each to the
 * scalar key Chronicle can actually print (see displayKeyFor), so a column can
 * be declared as `signature_traits` and land in the manifest as
 * `signature_traits_display` without anyone having to remember the suffix.
 *
 * `fold: true` adds a "Details" column carrying everything NOT given its own
 * column, rendered into one string. It exists for the three rules files whose
 * entries are structurally heterogeneous — monster-building.json's twelve
 * entries between them use twenty-eight distinct property keys, most on a
 * single entry. Giving each its own column would produce a table that is
 * twenty-eight columns wide and ~4% populated; folding them keeps every fact
 * on the page in a table a person can read.
 *
 * Column counts are kept deliberately low. The list table is wrapped in
 * `overflow-hidden` and the table itself is `w-full`
 * (internal/systems/system_pages.templ), so extra columns do not scroll — they
 * squeeze every other column until the text wraps one word per line.
 */
export const CATEGORIES = [
  {
    file: 'abilities.json',
    slug: 'abilities',
    name: 'Abilities',
    icon: 'fa-bolt',
    fold: true,
    // cost_amount / cost_resource are the machine-readable halves of `cost`
    // ("5 Wrath"), kept for widgets. Folding them into Details would print
    // "cost amount — 5 · cost resource — Wrath" under a Cost row that already
    // says it, on 361 of 519 abilities.
    foldExclude: ['cost_amount', 'cost_resource'],
    columns: [
      ['category', 'Granted By', 'string'],
      ['class', 'Class', 'string'],
      ['level', 'Level', 'number'],
      ['type', 'Type', 'string'],
      ['action_type', 'Action', 'string'],
      ['cost', 'Cost', 'string'],
      ['keywords', 'Keywords', 'string'],
      ['distance', 'Distance', 'string'],
      ['target', 'Target', 'string'],
      ['power_roll', 'Power Roll', 'string'],
      ['tier1', 'Tier 1 (11 or lower)', 'string'],
      ['tier2', 'Tier 2 (12-16)', 'string'],
      ['tier3', 'Tier 3 (17+)', 'string'],
      ['effect', 'Effect', 'string'],
      ['trigger', 'Trigger', 'string'],
    ],
  },
  {
    file: 'ancestries.json',
    slug: 'ancestries',
    name: 'Ancestries',
    icon: 'fa-dna',
    fold: true,
    columns: [
      ['size', 'Size', 'string'],
      ['speed', 'Speed', 'number'],
      ['stability', 'Stability', 'number'],
      ['ancestry_points', 'Ancestry Points', 'number'],
      ['quick_build', 'Quick Build', 'string'],
      ['signature_traits', 'Signature Traits', 'string'],
      ['purchased_traits', 'Purchased Traits', 'string'],
    ],
  },
  {
    file: 'kits.json',
    slug: 'kits',
    name: 'Kits',
    icon: 'fa-toolbox',
    columns: [
      ['type', 'Type', 'string'],
      ['armor', 'Armor', 'string'],
      ['weapon', 'Weapon', 'string'],
      ['equipment', 'Equipment', 'string'],
      ['stamina_bonus', 'Stamina Bonus', 'number'],
      ['stamina_bonus_scaling', 'Stamina Scaling', 'string'],
      ['speed_bonus', 'Speed Bonus', 'number'],
      ['stability_bonus', 'Stability Bonus', 'number'],
      ['melee_damage_bonus', 'Melee Damage', 'string'],
      ['ranged_damage_bonus', 'Ranged Damage', 'string'],
      ['melee_distance_bonus', 'Melee Distance', 'number'],
      ['ranged_distance_bonus', 'Ranged Distance', 'number'],
      ['disengage_bonus', 'Disengage Bonus', 'number'],
      ['signature_ability', 'Signature Ability', 'string'],
    ],
  },
  {
    file: 'creatures.json',
    slug: 'creatures',
    name: 'Creatures',
    icon: 'fa-paw',
    columns: [
      ['level', 'Level', 'number'],
      ['organization', 'Organization', 'string'],
      ['role', 'Role', 'string'],
      ['ev', 'EV', 'number'],
      ['size', 'Size', 'string'],
      ['stamina', 'Stamina', 'number'],
      ['speed', 'Speed', 'number'],
      ['free_strike', 'Free Strike', 'string'],
      ['keywords', 'Keywords', 'string'],
      ['traits', 'Traits', 'string'],
    ],
  },
  {
    file: 'creature-abilities.json',
    slug: 'creature-abilities',
    name: 'Creature Abilities',
    icon: 'fa-burst',
    columns: [
      ['type', 'Type', 'string'],
      ['keywords', 'Keywords', 'string'],
      ['distance', 'Distance', 'string'],
      ['target', 'Target', 'string'],
      ['power_roll', 'Power Roll', 'string'],
      ['tier1', 'Tier 1 (11 or lower)', 'string'],
      ['tier2', 'Tier 2 (12-16)', 'string'],
      ['tier3', 'Tier 3 (17+)', 'string'],
      ['effect', 'Effect', 'string'],
      ['trigger', 'Trigger', 'string'],
      ['villain_action_order', 'VA Order', 'string'],
    ],
  },
  {
    file: 'animal-traits.json',
    slug: 'animal-traits',
    name: 'Animal Traits',
    icon: 'fa-hippo',
    fold: true,
    columns: [
      ['group', 'Group', 'string'],
      ['cost', 'Cost', 'number'],
      ['repeatable', 'Repeatable', 'number'],
      ['upgrade', 'Upgrade', 'string'],
      ['optional', 'Optional', 'string'],
      ['granted_ability', 'Granted Ability', 'string'],
    ],
  },
  {
    file: 'ancestry-point-buy.json',
    slug: 'ancestry-point-buy',
    name: 'Ancestry Point Buy',
    icon: 'fa-scale-balanced',
    fold: true,
    // `category` is a constant marker on every entry of the file and just
    // repeats the category name the page is already under.
    foldExclude: ['category'],
    columns: [['rule_type', 'Rule Type', 'string']],
  },
  {
    file: 'monster-building.json',
    slug: 'monster-building',
    name: 'Monster Building',
    icon: 'fa-dragon',
    fold: true,
    // `category` is a constant marker on every entry of the file and just
    // repeats the category name the page is already under.
    foldExclude: ['category'],
    columns: [
      ['rule_type', 'Rule Type', 'string'],
      ['formula', 'Formula', 'string'],
      ['rounding', 'Rounding', 'string'],
    ],
  },
  {
    file: 'encounter-building.json',
    slug: 'encounter-building',
    name: 'Encounter Building',
    icon: 'fa-chess-board',
    fold: true,
    // `category` is a constant marker on every entry of the file and just
    // repeats the category name the page is already under.
    foldExclude: ['category'],
    columns: [
      ['rule_type', 'Rule Type', 'string'],
      ['difficulty', 'Difficulty', 'string'],
      ['budget_band', 'Budget Band', 'string'],
      ['victories', 'Victories', 'string'],
    ],
  },
  {
    file: 'rules-glossary.json',
    slug: 'rules-glossary',
    name: 'Rules Glossary',
    icon: 'fa-book',
    // The definition itself is the root `description`, which the detail page
    // renders on its own and the list table shows through the derived summary.
    // The category it belongs to is all the table needs to add.
    columns: [['category', 'Category', 'string']],
  },
  {
    file: 'skills.json',
    slug: 'skills',
    name: 'Skills',
    icon: 'fa-graduation-cap',
    columns: [['group', 'Group', 'string']],
  },
  {
    file: 'ability-keywords.json',
    slug: 'ability-keywords',
    name: 'Ability Keywords',
    icon: 'fa-tags',
    columns: [
      ['group', 'Group', 'string'],
      ['note', 'Note', 'string'],
    ],
  },
  {
    file: 'creature-keywords.json',
    slug: 'creature-keywords',
    name: 'Creature Keywords',
    icon: 'fa-hashtag',
    // No properties at all: name + the derived summary + the root description
    // on the detail page are the entire entry.
    columns: [],
  },
];

/** CATEGORIES indexed by data filename. */
export const CATEGORY_BY_FILE = new Map(CATEGORIES.map((c) => [c.file, c]));

// ---------------------------------------------------------------------------
// Which files the reference browser shows
// ---------------------------------------------------------------------------

/**
 * WIDGET_ONLY names the data/*.json files that are deliberately NOT reference
 * categories: they are read by a widget or by the monster engine, and browsing
 * them as a table of rows would show implementation detail rather than rules.
 *
 * The list is exhaustive on purpose. tools/test-render-contract.mjs asserts
 * that every data file is either a manifest category or named here, so a new
 * dataset can never again land in data/ and be invisible in the product
 * because nobody remembered to declare it.
 */
export const WIDGET_ONLY = new Set([
  // Legacy root-field shape, read straight off the root by monster-engine.js
  // and monster-builder.js. Their published equivalents are browsable as the
  // monster-building category.
  'organization-templates.json',
  'role-templates.json',
  // One synthetic row of pre-computed numbers, consumed by monster-builder.js.
  'damage-baselines.json',
  // Rulebook UI content: layout blocks and a scripted example, consumed by the
  // rulebook-frontpage widget and the example player.
  'rulebook-frontpage.json',
  'rulebook-examples.json',
]);

/**
 * SOURCE_PENDING names the files whose entries do NOT yet carry provenance.
 *
 * docs/DATA-SCHEMA.md states the provenance rule as a contract; this set is the
 * exact, enumerated extent of the exception, and test-render-contract.mjs pins
 * it both ways — a file here that has been sourced must be removed from the
 * set, and a file NOT here must be fully sourced. So the list can only shrink,
 * and a new data file can never be added to it.
 *
 * These four predate the provenance rule. Sourcing them means citing a book and
 * chapter per entry, which has to be read off the published text rather than
 * recalled; guessing a citation would be worse than admitting it is missing.
 */
export const SOURCE_PENDING = new Set([
  'rules-glossary.json',
  'skills.json',
  'creature-abilities.json',
  'creature-keywords.json',
  'rulebook-frontpage.json',
]);
